### ISSUE TITLE
Problems with documentation

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#615]
Hi @miguelriemoliveira 

The evaluation commands from the point (https://lardemua.github.io/atom_documentation/evaluations/#rgb-to-depth-camera-evaluation) down don't match the scripts in the atom evaluation folder

**Comment by miguelriemoliveira** [comment]
Fixed. Thanks.

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira ,

This still isn't fixed for the sections "LiDAR to LiDAR evaluation" and "LiDAR to RGB evaluation". The evaluation script files in the documentation do not exist in ATOM. Somewhere along the way, those files must've changed names

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

can you fix the documentation please?
