### ISSUE TITLE
Zau Calibration

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#968]
Hello @miguelriemoliveira and @Kazadhum 

As you know, I have unsuccessfully tried to calibrate Zau before.
This issue serves for us to solve this problem.

In order to solve this, we need to know what was done beforehand.

Firstly, I tried a full system calibration with:

```
rosrun atom_calibration calibrate -json $ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected.json -v -uic -csf 'lambda x: int(x) not in []' -ssf 'lambda x: x not in ["vo_body_fisheye1", "vo_body_fisheye2"]'
```

Which was very slow, so I only retrieved the first iteration, which speaks for itself.

```bash
+------------+----------------+---------------------------------+----------------------------+-----------------------+---------------------+                                                                       
| Collection | lidar_body [m] |        rgb_body_left [px]       |    rgb_body_right [px]     |  rgbd_hand_color [px] | rgbd_hand_depth [m] |                                                                       
+------------+----------------+---------------------------------+----------------------------+-----------------------+---------------------+                                                                       
|    000     |     0.1939     |               ---               |           0.2790           |          ---          |        0.6864       |                                                                       
|    001     |     0.1946     |               ---               |           0.2585           |        740.4794       |        0.3272       |                                                                       
|    002     |     0.3040     |             290.2946            |            ---             |       1544.3119       |        1.4707       |                                                                       
|    003     |     0.3038     |             290.6028            |            ---             |        760.4435       |        0.7229       |                                                                       
|    004     |     0.2496     |             346.4650            |            ---             |       1125.9515       |        1.0762       |                                                                       
|    005     |     0.2514     |             348.3987            |            ---             |        457.5135       |        0.3631       |                                                                       
|    007     |     0.3194     |               ---               |          141.6305          |          ---          |        1.6258       |                                                                       
|    008     |     0.3211     |               ---               |          142.0877          |          ---          |        0.9749       |                                                                       
|    009     |     0.3215     |               ---               |          140.8030          |        552.3251       |        0.3778       |                                                                       
|    010     |     0.3386     |               ---               |          201.1773          |        385.5437       |        0.4151       |                                                                       
|    011     |     0.3359     |               ---               |          200.9437          |        818.3611       |        0.8434       |                                                                       
|    012     |     0.4125     |               ---               |          334.8205          |        512.5840       |        0.2317       |                                                                       
|    013     |     1.1362     |        457821141506.8017        |            ---             |       41065.8179      |        0.6442       |                                                                       
|    014     |     0.9936     |               ---               |         14783.0109         |          ---          |         ---         |                                                                       
|    015     |     0.9894     |               ---               |         14844.2871         |       2385.7146       |        1.1079       |                                                                       
|    016     |     2.0224     |               ---               | 590681790428008022016.0000 | 4249926467125768.0000 |        1.8657       |                                                                       
|    017     |     1.9985     |               ---               |    724095704629585.5000    |       3129.8646       |        1.2227       |                                                                       
|    018     |     1.9973     |               ---               |    758499678056853.7500    |       3360.5949       |        1.2279       |                                                                       
|    019     |     2.1069     |               ---               |    777227631612041.0000    |       3489.5101       |        1.1408       |                                                                       
|    020     |     2.1440     | 47906817194096436950597632.0000 |            ---             |     355103825.9580    |        2.8356       |                                                                       
|    021     |     2.1603     |   1148544782966324985856.0000   |            ---             |     14331041.9931     |        1.9194       |                                                                       
|    022     |     2.1723     |   1148544782966324985856.0000   |            ---             |     14318005.4360     |        1.9197       |
|    024     |     2.1337     |               ---               |        1191711.6395        |          ---          |        0.3958       |
|    025     |     2.1174     |               ---               |        1116122.1382        |        885.2455       |        1.5117       |
|    026     |     2.6738     |               ---               |       11687309.1259        |      386324.8061      |        1.8028       |
|    027     |     2.6722     |               ---               |       10984409.7375        |      491618.1919      |        1.8181       |
|    028     |     2.6772     |               ---               |       11150094.8619        |  63638306458559.6250  |        1.9609       |
|    029     |     2.7334     |             886.0851            |            ---             |          ---          |        2.4232       |
|    030     |     2.7336     |             889.6913            |            ---             |       88040.1836      |        1.9992       |
|    031     |     2.7362     |             892.0146            |            ---             |          ---          |        2.0286       |
|    032     |     2.7642     |             892.0168            |            ---             |       37231.9843      |        2.0115       |
|    033     |     3.0139     |             716.5487            |            ---             |       4658.1998       |        2.3001       |
|    034     |     3.0400     |             735.9727            |            ---             |       67295.5261      |        1.5374       |
|    035     |     3.0144     |             735.2294            |            ---             |          ---          |        1.2621       |
|    036     |     3.0396     |             735.2112            |            ---             |       21235.0739      |        2.0732       |                                                                       
|    037     |     2.7757     |               ---               |         1207.6261          |          ---          |        0.4974       |                                                                       
|    038     |     2.7790     |               ---               |         1160.5614          |  115674160710200.3438 |        1.9120       |                                                                       
|    039     |     3.2655     |            1889.2326            |            ---             |        816.1449       |        2.9535       |                                                                       
|    040     |     3.3047     |            1892.1805            |            ---             |      185090.0432      |        2.1985       |                                                                       
|    041     |     3.4714     |             759.3787            |            ---             |       17525.8960      |        2.6247       |                                                                       
|    042     |     3.4724     |             759.7154            |            ---             |      321890.1698      |        2.5588       |                                                                       
|    043     |     3.4466     |               ---               |          537.9997          |          ---          |        1.6992       |                                                                       
|    044     |     3.4472     |               ---               |          537.6438          |       1538.3960       |        2.3883       |                                                                       
|    045     |     3.4000     |             698.2542            |            ---             |          ---          |        1.7936       |                                                                       
|    046     |     3.4019     |             698.7456            |            ---             |       2462.2971       |        2.0478       |
|    047     |     3.4121     |             559.3476            |            ---             |       2571.7904       |        2.0123       |
|    048     |     3.4442     |               ---               |          561.5529          |          ---          |        1.5040       |
|    049     |     3.4390     |               ---               |          561.7097          |       1269.8759       |        2.3044       |
|    050     |     3.4979     |            1043.1360            |            ---             |          ---          |        3.1095       |
|    051     |     3.5562     |            1067.7023            |            ---             |       18202.3933      |        2.0908       |
|    052     |     3.5002     |             978.5816            |            ---             |       22017.2079      |        2.0885       |
|    053     |     3.8724     |               ---               |          186.2357          |          ---          |         ---         |
|    054     |     3.8735     |               ---               |          186.2374          |          ---          |         ---         |
|    055     |     3.8763     |               ---               |          187.3282          |          ---          |         ---         |
|    056     |     3.8383     |               ---               |          186.1986          |          ---          |         ---         |
|    057     |     3.8731     |               ---               |          186.2043          |        988.3034       |        3.0661       |
|    058     |     1.0707     |             371.1998            |            ---             |       1078.7850       |        1.2255       |
|    059     |     1.0929     |             372.2222            |            ---             |        740.1222       |        0.8485       |
|  Averages  |     2.2712     |  1711039795845101051183104.0000 | 19689468341701951488.0000  |  108030227311736.8594 |        1.6047       |
+------------+----------------+---------------------------------+----------------------------+-----------------------+---------------------+

```
---
Then, I tried running with only one RGB sensor (`rgb_body_left`):

```
rosrun atom_calibration calibrate -json $ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected.json -v -uic -csf 'lambda x: int(x) not in []' -ssf 'lambda x: x in ["rgb_body_left"]'
```

Which gave the large results:

```bash
+------------+-------------------------------+                                                                                                                                                                     
| Collection |       rgb_body_left [px]      |                                                                                                                                                                     
+------------+-------------------------------+                                                                                                                                                                     
|    000     |              ---              |                                                                                                                                                                     
|    001     |              ---              |                                                                                                                                                                     
|    002     |           32038.0684          |                                                                                                                                                                     
|    003     |            435.6367           |                                                                                                                                                                     
|    004     |           14915.7530          |                                                                                                                                                                     
|    005     |           14210.5000          |                                                                                                                                                                     
|    007     |              ---              |                                                                                                                                                                     
|    008     |              ---              |                                                                                                                                                                     
|    009     |              ---              |                                                                                                                                                                     
|    010     |              ---              |                                                                                                                                                                     
|    011     |              ---              |                                                                                                                                                                     
|    012     |              ---              |                                                                                                                                                                     
|    013     |            998.5183           |                                                                                                                                                                     
|    014     |              ---              |                                                                                                                                                                     
|    015     |              ---              |                                                                                                                                                                     
|    016     |              ---              |                                                                                                                                                           
|    017     |              ---              |                                                                                                                                                                     
|    018     |              ---              |                                                                                                                                                                     
|    019     |              ---              |                                                                                                                                                                     
|    020     | 149958598572536017977344.0000 |                                                                                                                                                                     
|    021     |    2686866805465288192.0000   |                                                                                                                                                                     
|    022     |    2687526301505190912.0000   |                                                                                                                                                                     
|    024     |              ---              |                                                                                                                                                                     
|    025     |              ---              |                                                                                                                                                                     
|    026     |              ---              |
|    027     |              ---              |
|    028     |              ---              |
|    029     |            137.6338           |
|    030     |            210.3190           |
|    031     |            416.2567           |
|    032     |            701.6728           |
|    033     |   31986668580686155776.0000   |
|    034     |           33497.4328          |
|    035     |           22472.8641          |
|    036     |           16031.8150          |
|    037     |              ---              |
|    038     |              ---              |
|    039     |            786.5103           |
|    040     |            370.3936           |
|    041     |           4372.6043           |
|    042     |            798.2973           |
|    043     |              ---              |
|    044     |              ---              |
|    045     |      12781422464709.2109      |
|    046     |           8826.1144           |
|    047     |            503.4703           |
|    048     |              ---              |
|    049     |              ---              |
|    050     |            610.5976           |
|    051     |            586.9684           |
|    052     |            227.0040           |
|    053     |              ---              |
|    054     |              ---              |
|    055     |              ---              |
|    056     |              ---              |
|    057     |              ---              |
|    058     |         21501579.1680         |
|    059     |            996.1618           |
|  Averages  |  5356998558821611732992.0000  |
+------------+-------------------------------+

```
---
I also tried with `rgb_body_right`:

```
rosrun atom_calibration calibrate -json $ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected.json -v -uic -csf 'lambda x: int(x) not in []' -ssf 'lambda x: x in ["rgb_body_right"]'

```

Which gave the comparable results:

```bash
+------------+-----------------------+                                                                                                                                                                             
| Collection |  rgb_body_right [px]  |                                                                                                                                                                             
+------------+-----------------------+                                                                                                                                                                             
|    000     |        276.4820       |                                                                                                                                                                             
|    001     |       4230.0239       |
|    002     |          ---          |
|    003     |          ---          |
|    004     |          ---          |
|    005     |          ---          |
|    007     |        930.3981       |
|    008     |        184.5898       |
|    009     |        324.1031       |
|    010     |     151360364.5828    |
|    011     |        408.3377       |
|    012     |       1594.4110       |
|    013     |          ---          |
|    014     |     142995494.7041    |
|    015     |       54681.3206      |                                                                                                                                                                     
|    016     | 7437123934081352.0000 |                                                                                                                                                                             
|    017     |  195957387209433.6250 |                                                                                                                                                                             
|    018     |  416827417341844.4375 |                                                                                                                                                                             
|    019     |  147768854410930.8750 |                                                                                                                                                                             
|    020     |          ---          |                                                                                                                                                                             
|    021     |          ---          |                                                                                                                                                                             
|    022     |          ---          |                                                                                                                                                                             
|    024     |        190.1252       |                                                                                                                                                                             
|    025     |        137.8121       |                                                                                                                                                                             
|    026     |        814.9722       |
|    027     |        145.8996       |
|    028     |        188.6021       |
|    029     |          ---          |
|    030     |          ---          |
|    031     |          ---          |
|    032     |          ---          |
|    033     |          ---          |
|    034     |          ---          |
|    035     |          ---          |
|    036     |          ---          |
|    037     |        562.4682       |
|    038     |        750.1641       |
|    039     |          ---          |
|    040     |          ---          |
|    041     |          ---          |
|    042     |          ---          |
|    043     |        272.7874       |
|    044     |       23996.1769      |
|    045     |          ---          |
|    046     |          ---          |
|    047     |          ---          |
|    048     |        311.9811       |
|    049     |        948.0704       |
|    050     |          ---          |
|    051     |          ---          |
|    052     |          ---          |
|    053     |        537.8379       |
|    054     |       32928.7113      |
|    055     |      1042699.1782     |
|    056     |       4590.4506       |
|    057     |        696.7587       |
|    058     |          ---          |
|    059     |          ---          |
|  Averages  |  273255929619060.7188 |
+------------+-----------------------+

```

---
Then, I tried only using a small number of collections:

```
rosrun atom_calibration calibrate -json $ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected.json -v -uic -csf 'lambda x: int(x) < 12' -ssf 'lambda x: x in ["rgb_body_right"]'
```

Which gave a much more reasonable results:

```bash
+------------+---------------------+
| Collection | rgb_body_right [px] |
+------------+---------------------+
|    000     |        0.2822       |
|    001     |        0.2675       |
|    002     |         ---         |
|    003     |         ---         |
|    004     |         ---         |
|    005     |         ---         |
|    007     |        0.4034       |
|    008     |        0.3665       |
|    009     |        0.3639       |
|    010     |        0.3488       |
|    011     |        0.3184       |
|  Averages  |        0.3358       |
+------------+---------------------+
```
---
From this good result, I tried adding the other RGB body sensor:

```
rosrun atom_calibration calibrate -json $ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected.json -v -uic -csf 'lambda x: int(x) < 12' -ssf 'lambda x: x in ["rgb_body_right", "rgb_body_left"]'
```

Which gave me (also) reasonable results:

```bash
+------------+--------------------+---------------------+
| Collection | rgb_body_left [px] | rgb_body_right [px] |
+------------+--------------------+---------------------+
|    000     |        ---         |        0.3360       |
|    001     |        ---         |        0.2611       |
|    002     |       0.2910       |         ---         |
|    003     |       0.3206       |         ---         |
|    004     |       0.3230       |         ---         |
|    005     |       0.3186       |         ---         |
|    007     |        ---         |        0.3988       |
|    008     |        ---         |        0.3650       |
|    009     |        ---         |        0.3621       |
|    010     |        ---         |        0.4539       |
|    011     |        ---         |        0.3853       |
|  Averages  |       0.3133       |        0.3660       |
+------------+--------------------+---------------------+
```

---

From this, I tried using all collections again, but removing the ones with most outrageous values:

```
rosrun atom_calibration calibrate -json $ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected.json -v -uic -csf 'lambda x: int(x) not in [13, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]' -ssf 'lambda x: x in ["rgb_body_right", "rgb_body_left"]'
```

Which after 850 iterations gave me the results:

```bash
+------------+--------------------+---------------------+                                                                                                                                                          
| Collection | rgb_body_left [px] | rgb_body_right [px] |                                                                                                                                                          
+------------+--------------------+---------------------+                                                                                                                                                          
|    000     |        ---         |       14.7500       |                                                                                                                                                          
|    001     |        ---         |       14.6533       |                                                                                                                                                          
|    002     |      28.0920       |         ---         |                                                                                                                                                          
|    003     |      27.3911       |         ---         |  
|    004     |      37.3374       |         ---         |                                                                                                                                                          
|    005     |      37.3375       |         ---         |                                                                                                                                                          
|    007     |        ---         |       18.9166       |                                                                                                                                                          
|    008     |        ---         |       19.4154       |
|    009     |        ---         |       17.6934       |
|    010     |        ---         |       13.8320       |
|    011     |        ---         |       13.8024       |
|    012     |        ---         |       23.7511       |
|    014     |        ---         |       447.9186      |
|    015     |        ---         |       447.9565      |
|    029     |      105.7806      |         ---         |
|    030     |      105.4818      |         ---         |
|    031     |      103.6028      |         ---         |
|    032     |      103.6626      |         ---         |
|    033     |      113.5780      |         ---         |
|    034     |      112.5293      |         ---         |
|    035     |      112.5476      |         ---         |
|    036     |      112.5180      |         ---         |
|    037     |        ---         |       164.0562      |
|    038     |        ---         |       160.3851      |
|    039     |      86.3684       |         ---         |
|    040     |      86.3311       |         ---         |
|    041     |      116.2789      |         ---         |
|    042     |      116.2683      |         ---         |
|    043     |        ---         |       20.4166       |
|    044     |        ---         |       20.4388       |
|    045     |      79.5114       |         ---         |
|    046     |      116.8722      |         ---         |
|    047     |      13.8244       |         ---         |
|    048     |        ---         |       55.9538       |
|    049     |        ---         |       111.2607      |
|    050     |      111.4629      |         ---         |
|    051     |      110.5135      |         ---         |
|    052     |      113.8704      |         ---         |
|    053     |        ---         |       15.0536       |
|    054     |        ---         |       15.0672       |
|    055     |        ---         |       16.1876       |
|    056     |        ---         |       15.0845       |
|    057     |        ---         |       15.0779       |
|    058     |      14.4713       |         ---         |
|    059     |      14.6249       |         ---         |
|  Averages  |      82.5107       |       78.1748       |
+------------+--------------------+---------------------+
```

**Comment by miguelriemoliveira** [comment]
Thanks @manuelgitgomes for the detailed description. It should allow me to replicate the experiments with the odometry corrected and evaluate the differences.

One question: are you using @brunofavs approach of calibrating the odometry transformation or these results are all without calibrating the odometry?

**Comment by manuelgitgomes** [comment]
Hello!

These results are with Bruno's approach!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by miguelriemoliveira** [comment]
Thanks @manuelgitgomes .

I just finished correcting the odometry in the zau dataset ... 59 collections ... uff.

Now I will try to calibrate and post results asap.

**Comment by miguelriemoliveira** [comment]
> I also tried with rgb_body_right:

Before Averages  |  273255929619060.7188 
Now Averages  |        0.3023       

> Then, I tried only using a small number of collections:

Before Averages  |        0.3358       
Now Averages  |        0.3302       |

I suspect this small group of collections were all with consistent odometry as it only jumps from time to time.

> Which after 850 iterations gave me the results:

Before Averages  |      82.5107       |       78.1748   
Now Averages  |       0.3663       |        0.3157       

Later on I will try the full calibration, but for now it looks good.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

> These results are with Bruno's approach!

But I was looking into the calibration/config.yaml file and in the additional tfs the odometry itransform s not included.

```yml
# ATOM will calibrate the extrinsic parameters of your links.
# In this section you should discriminate the additional transformations that will be part of the calibrations.
additional_tfs:
  # Each key will define a transformations and its name, which will be use throughout the calibration.
  # Each additional transformations definition must have the following properties:
  #
  #       parent_link:
  #           The parent link of the transformation (i.e. link) to be calibrated.
  #
  #       child_link:
  #           This is the transformation (i.e. link) that we be optimized.
  #
  # EXAMPLE:
  base_link_mb_to_base_link:
   parent_link: "base_link_mb"
   child_link: "base_link"x
```

[This is the complete file ](https://github.com/lardemua/zau/blob/main/zau_calibration/calibration/config.yml)

That means we are not calibrating the odometry, right? 
Perhaps you ran before with a different config.yml file?

**Comment by miguelriemoliveira** [comment]
Hi again @manuelgitgomes ,

So I when to look at the dataset_corrected.json and in fact you have the calibration of the **world to base_footprint** transform.

![image](https://github.com/user-attachments/assets/5fcece40-90a9-4ae0-8aae-8d6e81198f4b)

It seems the config.yml is not up to date with the datasets. Did you forget to push something?

**Comment by miguelriemoliveira** [comment]
Results for two body cameras + lidar (taking some collections away)

    rosrun atom_calibration calibrate -json $ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected.json -v -uic -csf 'lambda x: int(x) not in [11,12, 30,33,51, 52]' -ssf 'lambda x: x not in ["vo_body_fisheye1", "vo_body_fisheye2", "rgbd_hand_color", "rgbd_hand_depth"]'

```
+------------+----------------+--------------------+---------------------+
| Collection | lidar_body [m] | rgb_body_left [px] | rgb_body_right [px] |
+------------+----------------+--------------------+---------------------+
|  Averages  |     0.0099     |       1.5042       |        2.1462       |
```

which is quite good. 
Running without the odometry calibration, i.e

    rosrun atom_calibration calibrate -json $ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected.json -v -uic -csf 'lambda x: int(x) not in [11,12, 30,33,51, 52]' -ssf 'lambda x: x not in ["vo_body_fisheye1", "vo_body_fisheye2", "rgbd_hand_color", "rgbd_hand_depth"]' -atsf "lambda x: x not in ['world_to_base_footprint']"


```
+------------+----------------+--------------------+---------------------+
| Collection | lidar_body [m] | rgb_body_left [px] | rgb_body_right [px] |
+------------+----------------+--------------------+---------------------+
|  Averages  |     0.0192     |       8.4854       |        8.8932       |
```
Which is much higher than before. Very good news. It means the odometry calibration is doing a lot of the work!

**Comment by brunofavs** [comment]
> Very good news. It means the odometry calibration is doing a lot of the work!

Indeed, these results are great :)

**Comment by manuelgitgomes** [comment]
Hello!

> That means we are not calibrating the odometry, right?
> Perhaps you ran before with a different config.yml file?

I am sorry, just checked I have uncommitted files.
That should now be solved.



> which is quite good.

These results are great!
This is going in the right direction.

**Comment by miguelriemoliveira** [comment]
> I am sorry, just checked I have uncommitted files.
> That should now be solved.

Humm ... I still do not have the config.yml listing the odometry transformation ...

**Comment by manuelgitgomes** [comment]
@miguelriemoliveira Well, then I could have added the additional_tf manually to the dataset :sweat_smile: 
If you want me to reconfigure zau, I can do it

**Comment by miguelriemoliveira** [comment]
> Well, then I could have added the additional_tf manually to the dataset

You do this to avoid having to create a new dataset right?

> If you want me to reconfigure zau, I can do it

No need. I can do it. Thanks.

**Comment by manuelgitgomes** [comment]
> You do this to avoid having to create a new dataset right?

Exactly.

**Comment by Kazadhum** [comment]
Just finished reading the issue and these results are a big improvement. Sounds like good progress!

**Comment by miguelriemoliveira** [comment]
Closing this issue. Will open a new one for the depth camera related issues (#975).
